# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f494d35ef63e86fa9e916a09d3855926dd862070c902d38b2c13e54f716c260e773ec12b43650a5b2bd1a46dbaaea853facb63f4042ff1107b01551a48525e58

test:
  secret_key_base: a5854a778b7ce6c7d0c2531ba638f6d48c9116a8c674f5339f5b11a7fe2e9f9b0a8ca67c6922494867836388f0c9c0d7c04d510450cddf1d8c3559e5166deea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
